nav:
  - 主页: # 主页/
    - index.md
    - 关于我: about.md
  - CS 课程:
    - CS课程/index.md
    - 计算机视觉导论:
      - 课程笔记: CS课程/计算机视觉导论.md
    - CS106L:
      - 课程笔记: CS课程/CS106L/CS106L课程笔记.md
      - 期中复习: CS课程/CS106L/CS106L-Midquarter-Review.md
  - 论文阅读:
    - 论文阅读/index.md
    - 3D Reconstruction:
      - NeRF: 论文阅读/reconstruction/NeRF.md
      - Depth-Gaussian: 论文阅读/reconstruction/Depth-Gaussian.md
    - Human Motion Generation:
      - Generating Continual Human Motion in Diverse 3D Scenes: 论文阅读/motion/Generating-Continual-Human-Motion-in-Diverse-3D-Scenes.md
      - TeSMo: 论文阅读/motion/Generating Human Interaction Motions in Scenes with Text Control.md
      - Generating Human Motion in 3D Scenes from Text Descriptions: 论文阅读/motion/Generating-Human-Motion-in-3D-Scenes-from-Text-Descriptions.md
      - GPT-Connect: 论文阅读/motion/GPT-Connect.md
      - Human Motion Generation Survey: 论文阅读/motion/Human-Motion-Generation-A-Survey.md

  - 杂项:
    - 杂项/11-25签到推.md
    - 杂项/code-before-this-website.md
    - 杂项/Complete-Binary-Search-Tree.md
    - 杂项/专业分流内训.md

site_name: 罹魂梦蝶の笔记空间
# site_url: https://zhang-each.github.io/My-CS-notebook/
# repo_name: Zhang-Each/My-CS-notebook
# repo_url: https://github.com/zhang-each/My-CS-notebook/

theme:
  name: material
  features:
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中 
  language: 'zh'
  palette:
    primary: black
    scheme: default
  font:
    text: Hiragino Sans GB # Palatino
    code: Roboto Mono
  # custom_dir: overrides # 用来搞评论的，参考 https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/


markdown_extensions:
  - toc:
      permalink: true # link for each title
      slugify: !!python/name:pymdownx.slugs.uslugify # enable Unicode link
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: underscore
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
copyright: '本页面的全部内容在 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a> 协议之条款下提供，附加条款亦可能应用。'

extra_css:
  - 'from_oi_wiki/css/extra.css?v=13'
  - css/status.css

extra_javascript:
  - 'from_oi_wiki/js/extra.js'
  # - js/mathjax.js # 支持数学公式，ref : https://squidfunk.github.io/mkdocs-material/reference/mathjax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # 支持表格排序
  # - js/tablesort.js
  - //busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

# plugins:
#   - search:
#       separator: '[\s\u200b\-]'
#   - git-revision-date-localized:
#       enable_creation_date: true
#       type: datetime
#       timezone: Asia/Shanghai
#       locale: zh
#   - statistics